channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - nb_conda
  - jupyterlab
  - dask-labextension
  - jupyterlab_code_formatter
  - jupyterlab_vim # jupyterlab-contrib/jupyterlab-vim
  - jupyterlab-git
  - geopandas
  - pygeos
  - pyogrio
  - dask
  - distributed
  - dask-geopandas
  - nodejs
  - xarray
  - netcdf4
  - numpy
  - pandas
  - matplotlib
  - folium
  - mapclassify
  - cartopy
  - contextily
  - pyarrow
  - rasterio
  - rioxarray
  - scikit-image
  - scikit-learn
  - scipy
  - bandit
  - isort
  - black
  - zarr
  - h5py
  - fiona
  - geojson
  - gcsfs
  - pystac
  - python-dotenv
  - tqdm
# TODO: resolve pip error
#  - pip3:
