name: ee

channels:
  - conda-forge

dependencies:
  - python=3.10
  - cartopy
  - contextily
  - dask
  - dask-labextension
  - earthengine-api
  - fiona
  - folium
  - gcsfs
  - geemap
  - geojson
  - geopandas
  - google-cloud-storage
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab_code_formatter
  - jupyterlab_vim # jupyterlab-contrib/jupyterlab-vim
  - matplotlib
  - nb_conda
  - netcdf4
  - nodefaults
  - numpy
  - pandas
  - pyarrow
  - pygeos
  - pyogrio
  - pystac
  - python-dotenv
  - rasterio
  - rioxarray
  - tqdm
  - xarray
  - zarr
  - dask-geopandas
  - hvplot
  - datashader
  - geoviews
  - spatialpandas
    
