name: coclico
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - geopandas
  - pygeos
  - pyogrio
  - xarray
  - netcdf4
  - numpy
  - pandas
  - matplotlib
  - folium
  - mapclassify
  - pyarrow
  - rasterio
  - rioxarray
  - jupyterlab
  - jupyterlab-git
  - bandit
  - jupyterlab_code_formatter
  - isort
  - black
  - zarr
  - h5py
  - nb_black
  - fiona
  - geojson
  - gcsfs
  - pystac
  - pystac-client
  - python-dotenv
  - datacube
  - google-cloud-storage
  - jupyterlab_vim
  - tqdm

# TODO: resolve pip error
#  - pip3:
#     - jupyterlab_tabnine
#     - xstac
#     - mapbox
#     - mapboxcli
