name: geo

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets
  - nb_conda
  - jupyterlab
  - nodejs
  - dask-labextension
  - dask_labextension
  - jupyterlab_code_formatter
  - jupyterlab_vim # jupyterlab-contrib/jupyterlab-vim
  - jupyterlab-git
  - geopandas
  - pygeos
  - pyogrio
  - dask
  - distributed
  - dask-geopandas
  - nodejs
  - xarray
  - netcdf4
  - numpy
  - pandas
  - matplotlib
  - folium
  - mapclassify
  - cartopy
  - contextily
  - pyarrow
  - rasterio
  - rioxarray
  - scikit-image
  - scikit-learn
  - scipy
  - bandit
  - isort
  - black
  - zarr
  - h5py
  - fiona
  - geojson
  - gcsfs
  - pystac
  - pystac-client
  - pydantic
  - python-dotenv
  - tqdm
  - datashader
  - spatialpandas
  - geoviews
  - hvplot
  
