#!/usr/bin/env bash

DOTFILES_ROOT="$HOME/.dotfiles"

dst="$DOTFILES_ROOT/vscode/code_extensions"
echo "Saving VSCode extensions $dst..."
echo "RUN code --list-extensions > $dst"
code --list-extensions > "$dst"

