name: torch
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.*
  - pip>=20
  - ipykernel
  - ipywidgets #  ipywidgets here and jupyterlab_widgets in jupyterlab env
  - ipyleaflet
  - adlfs
  - awscli
  - azure-data-tables
  - azure-identity
  - bandit
  - black
  - boto3
  - cartopy
  - cfgrib
  - click
  - dask
  - dask-cloudprovider
  - dask-geopandas
  - dask-ml
  - datacube
  - datashader
  - descartes
  - distributed
  - earthengine-api
  - eccodes>=2.24.2
  - fiona
  - folium
  - fsspec
  - gcsfs
  - geojson
  - geopandas>=0.11.0
  - geoviews
  - h5netcdf
  - h5py
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-xarray
  - isort
  - mapclassify
  - matplotlib
  - numpy
  - opencv
  - pandas
  - panel
  - planetary-computer
  - pooch
  - pyarrow
  - pydantic
  - pyogrio
  - python-dotenv
  - pytorch
  - pytorch-lightning
  - rasterio
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - spatialpandas
  - stac-geoparquet
  - stac-vrt
  - stackstac
  - torchgeo
  - torchvision
  - tqdm
  - wandb
  - zarr
  - pystac
  - pytest
  - pytest-cov
  - xarray
  - geoviews-core
