name: lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mamba==1.0.0
  - conda
  - pip
  - ca-certificates
  - certifi
  - openssl
  - jupyterlab
  - nodejs
  - pyviz::panel # needs to be in base to connect to widgets, not sure if it has to be from that channel
  - nb_conda_kernels
  - ipykernel
  # - ipywidgets # jupyterlab_widgets here and ipywidgets in project env
  - ipyleaflet
  - voila # downgrades jupyter_server to 1.23.5 which appears to break dask distributed but not sure..
  - jupyterlab_code_formatter
  - jupyterlab_vim
  - jupyterlab_widgets
  - jupyter-resource-usage # downgrades jupyter_server to 1.23.5 which appears to break dask distributed..
  - jupyter-panel-proxy # not sure if this one is really useful
  - jupyterlab-lsp # breaks tab complete if python-lsp-server not installed
  - python-lsp-server
  - jupyterlab-git
  - jupyterlab_execute_time
  - dask-labextension
  - jupyterlab-spellchecker
  - nbgitpuller
  # - lckr-jupyterlab-variableinspector  # doesn't work on my machine yet
  - black
  - isort
  # - click <8.0.4 # was proposed as solution for dask distributed error, but didnt work
  - gh-scoped-creds # check if useful
  - nbstripout
