name: lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.*
  - pip
  - black
  - ca-certificates
  - certifi
  - dask-labextension
  - gh-scoped-creds # check if useful
  - ghp-import
  - ipykernel
  - ipyleaflet
  - isort
  - jupyter-book
  - jupyter-panel-proxy # not sure if this one is really useful
  - jupyter-resource-usage
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab_execute_time # breaks env on windows installation
  - jupyterlab_vim
  - jupyterlab_widgets
  - jupyterlab-git
  - jupyterlab-lsp # breaks tab complete if python-lsp-server not installed
  - jupyterlab-spellchecker
  - poetry
  - pre_commit
  - nb_conda_kernels
  - nbgitpuller
  - nbstripout
  - nodejs
  - openssl
  - panel
  - python-lsp-server
  - pyviz_comms
  - voila
  - xeus-python
