name: testenv #
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.*
  - pip>=20
  - ipykernel # <6.21 # until https://github.com/dask/distributed/issues/7515 is solved
  - ipywidgets #  ipywidgets here and jupyterlab_widgets in jupyterlab env
  - ipyleaflet
  - adlfs
  - astropy
  - awscli
  - azure-data-tables
  - azure-identity
  - bandit
  - beautifulsoup4
  - black
  - boto3
  - cartopy
  - cfgrib
  - click
  - codespell
  - contextily
  - dask
  - dask-cloudprovider
  - dask-gateway
  - dask-geopandas
  - dask-ml
  - datacube
  - datashader
  - descartes
  - distributed
  - earthengine-api
  - eccodes>=2.24.2
  - fiona
  - flake8
  - folium
  - fsspec
  - gcsfs
  - geodatasets
  - geojson
  - geopandas>=0.11.0
  - geoviews-core
  - h3
  - h5netcdf
  - h5py
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - isort
  - lxml
  - mapclassify
  - matplotlib-base
  - mypy
  - numcodecs
  - numpy
  - odc-geo
  - odc-stac
  - opencv
  - pandas
  - panel
  - param
  - planetary-computer
  - pooch
  - pre-commit
  - pyarrow
  - pydantic
  - pyogrio
  - pytest
  - pytest-cov
  - python-dotenv
  - python-graphviz
  - pyyaml
  - rasterio
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - spatialpandas
  - stac-geoparquet
  - stac-vrt
  - stackstac
  - stactools
  - tabulate
  - tqdm
  - xarray-spatial
  - xvec
  - zarr
  - boltons
  - cattrs
  - ciso8601
  - dask-image
  - defusedxml
  - eodatasets3
  - jsonschema
  - jupyter-ui-poll
  - lmdb
  - numexpr
  - pims
  - pyrsistent
  - python-rapidjson
  - slicerator
  - structlog
  - zstandard
  - pip:
      - stactools-geoparquet-items
      - odc-ui
      - odc-stac
      - odc-stats
      - odc-algo
      - odc-io
      - odc-cloud[ASYNC]
      - odc-dscache
