name: jl-full
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version, pip, and other very generic libraries
  - python=3.11
  - pip>=20
  - ca-certificates
  - certifi
  - openssl
  - boltons
  - ciso8601
  - cattrs

    # Development Tools
  - bandit
  - black
  - click
  - codespell
  - flake8
  - isort
  - mypy
  - poetry
  - pre-commit
  - pydantic
  - pydantic
  - pytest
  - pytest-cov
  - ruff

  # Jupyterlab and lab extensions/packages
  - dask-labextension # causes slow startup on windows
  - gh-scoped-creds # check if useful
  - ipykernel
  - ipywidgets
  - jupyter-panel-proxy # not sure if this one is really useful
  - jupyter-resource-usage
  - jupyterlab_code_formatter
  - jupyterlab_execute_time # breaks env on windows installation
  - jupyterlab_vim # for vim users ^^
  - jupyterlab_widgets
  - jupyterlab-git # causes warning when git not on os
  - jupyterlab-lsp # breaks tab complete if python-lsp-server not installed
  - jupyterlab-spellchecker
  - jupyterlab>=4
  - nb_conda_kernels
  - nbgitpuller
  - nbstripout
  - nodejs
  - python-lsp-server
  - voila
  # - lckr-jupyterlab-variableinspector  # doesn't work on my machine yet

  # Jupyterbook dev tools
  - jupyter-book
  - nbformat

  # interactive vizualization libraries
  - bokeh
  - folium
  - geoviews
  - geoviews-core
  - holoviews=<1.18 # until bug in stream xy is fixed
  - hvplot
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyter_bokeh
  - matplotlib-base
  - panel
  - param

  # Data Science libraries
  - adlfs
  - astropy
  - awscli
  - azure-data-tables
  - azure-identity
  - beautifulsoup4
  - boto3
  - cartopy
  - cfgrib
  - contextily
  - dask
  - dask-cloudprovider
  - dask-geopandas
  - dask-image
  - dask-ml
  - dask-gateway
  - datacube
  - datashader
  - descartes
  - distributed
  - earthengine-api
  - eccodes>=2.24.2
  - fiona
  - fsspec
  - gcsfs
  - geodatasets
  - geojson
  - geopandas>=0.11.0
  - google-cloud-storage
  - h5netcdf
  - h5py
  - imbalanced-learn
  - intake
  - intake-esm
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - jsonschema
  - lightning=<2.0.9
  - lmdb
  - lxml
  - mapclassify
  - mercantile
  - netcdf4
  - numcodecs
  - numpy
  - odc-algo
  - odc-geo
  - odc-stac
  - openpyxl
  - pandas
  - pims
  - planetary-computer
  - pooch
  - pyarrow=10 # check if higher versions still bring cudatoolkit
  - pyogrio
  - python-dotenv
  - pytorch
  - pyyaml
  - rasterio
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - spatialpandas
  - stac-geoparquet
  - stac-vrt
  - stackstac
  - tabulate
  - timm>=0.9
  - toml
  - torchgeo
  - torchvision
  - tqdm
  - wandb
  - xarray
  - xarray-spatial
  - xgboost
  - xvec
  - zarr
  - zstandard

  # This is when you want the CoastalCodeBook package to be installed in dev mode
  - pip:
      # - -e .
      - antimeridian
    # - stactools-geoparquet-items
    # - odc-ui
    # - odc-stats
